language: python
sudo: required
dist: trusty
cache: pip
git:
  depth: 3
  quiet: true
python:
  - "3.6"
install:
  - pip install -r requirements.txt --quiet
script:
  - python -m unittest discover -s tests -t tests