language: python
sudo: required
dist: trusty
cache: pip
git:
  depth: 3
  quiet: true
branches:
  only:
  - /.*/
python:
  - "3.6"
install:
  - python setup.py install >/dev/null
script:
  - python -m unittest discover -s tests -t tests